name: Test Extension
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: pip install -r requirements.txt
      - name: test
        run: pytest --cov=. --cov-report lcov
      - name: upload coverage
        uses: codecov/codecov-action@v3

